### ISSUE TITLE
Bug in the bundled version of Mozilla Rhino

### ISSUE THREAD

**Issue by stefbo** [fornwall/eclipsescript#8]
There is a bug in the bundled version of Mozilla Rhino with JavaAdapter that makes it hard to subclass various Java classes and thus to use EclipseScript. See https://bugzilla.mozilla.org/show_bug.cgi?id=473185 and/or try to execute

var timer = new java.util.Timer()
var task = new JavaAdapter(java.util.TimerTask, {  run : function () { print("YO") } }) 
timer.schedule(task, 2000)

Error is:

Plug-in name: EclipseScript
Plug-in ID: org.eclipsescript
Version: 1.0.6

java.lang.NoSuchMethodException: adapter1.<init>(org.eclipsecript.rhino.javascript.Scriptable, org.eclipsecript.rhino.javascript.ContextFactory)
    at java.lang.Class.getConstructor0(Class.java:2721)
    at java.lang.Class.getConstructor(Class.java:1674)
    at org.eclipsecript.rhino.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:205)
    at org.eclipsecript.rhino.javascript.JavaAdapter.execIdCall(JavaAdapter.java:86)
    at org.eclipsecript.rhino.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
    at org.eclipsecript.rhino.javascript.BaseFunction.construct(BaseFunction.java:343)
    at org.eclipsecript.rhino.javascript.Interpreter.interpretLoop(Interpreter.java:1519)
    at org.eclipsecript.rhino.javascript.Interpreter.interpret(Interpreter.java:815)
    at org.eclipsecript.rhino.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
    at org.eclipsecript.rhino.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
    at org.eclipsescript.javascript.CustomContextFactory.doTopCall(CustomContextFactory.java:32)
    at org.eclipsecript.rhino.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
    at org.eclipsecript.rhino.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
    at org.eclipsecript.rhino.javascript.Context.evaluateReader(Context.java:1110)
    at org.eclipsescript.javascript.JavascriptRuntime.evaluate(JavascriptRuntime.java:121)
    at org.eclipsescript.javascript.JavaScriptLanguageSupport$1.run(JavaScriptLanguageSupport.java:38)
    at org.eclipsecript.rhino.javascript.Context.call(Context.java:489)
    at org.eclipsecript.rhino.javascript.ContextFactory.call(ContextFactory.java:504)
    at org.eclipsescript.javascript.JavaScriptLanguageSupport.executeScript(JavaScriptLanguageSupport.java:22)
    at org.eclipsescript.scripts.ScriptStore$2.call(ScriptStore.java:52)
    at org.eclipsescript.scripts.ScriptStore$2.call(ScriptStore.java:1)
    at org.eclipsescript.scripts.ScriptStore.executeRunnableWhichMayThrowScriptException(ScriptStore.java:26)
    at org.eclipsescript.scripts.ScriptStore.executeScript(ScriptStore.java:49)
    at org.eclipsescript.core.RunCurrentHandler.doExecute(RunCurrentHandler.java:27)
    at org.eclipsescript.ui.ErrorHandlingHandler.execute(ErrorHandlingHandler.java:16)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:76)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:231)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:212)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:131)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:171)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:277)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:496)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:547)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:368)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:314)
    at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:83)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1552)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1391)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1416)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1401)
    at org.eclipse.swt.widgets.Control.traverse(Control.java:5164)
    at org.eclipse.swt.widgets.Control.translateMnemonic(Control.java:5065)
    at org.eclipse.swt.widgets.Composite.translateMnemonic(Composite.java:1552)
    at org.eclipse.swt.widgets.Control.translateMnemonic(Control.java:5084)
    at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3169)
    at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:758)
    at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2092)
    at org.eclipse.swt.widgets.Control.windowProc(Control.java:5334)
    at org.eclipse.swt.widgets.Display.windowProc(Display.java:4532)
    at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
    at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:8549)
    at org.eclipse.swt.widgets.Display.eventProc(Display.java:1241)
    at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
    at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2281)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3324)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1049)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:939)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:79)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:587)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:542)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1443)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1419)

**Comment by dingjibang** [comment]
We have a class A:
    public class A {
        public static void createB(){
            Context ctx = Game.getJSContext();
            ScriptableObject scope = ctx.initStandardObjects(null, true);
            Object obj = ctx.evaluateString(scope, "new JavaAdapter(" + B.class.getName() + ", {})", null, 1, null);
            B adapter = (B)Context.jsToJava(obj, B.class);//THROW EXCEPTION
            Context.exit();
        }
    
        public void create() { }
    }

and blank class B:
    public class B {}

and main:
	Context ctx = Game.getJSContext();
	ScriptableObject scope = ctx.initStandardObjects(null, true);
	Object obj = ctx.evaluateString(scope, "new JavaAdapter(" + A.class.getName() + ", {create: function(){"+A.class.getName() +".get()}})", null, 1, null);
	A adapter = (A)Context.jsToJava(obj, A.class);
	adapter1.create();
	Context.exit();


the A.createB() is called by JS(not java, it's working if java)
